// Скрины хаба v5 для визуальной проверки. node run-e2e.mjs shots-hub.mjs
async (page) => {
  const log = [];
  const OUT = '/private/tmp/claude-501/-Users-meriler-cc-vault/76e257ae-ad97-4cdb-b63f-4a560bc65f29/scratchpad/shots';
  const shot = async (n) => { await page.screenshot({ path: `${OUT}/${n}.png` }); log.push(n); };
  const waitVis = (sel, t = 30000) => page.waitForFunction((s) => { const e = document.querySelector(s); return !!e && !e.classList.contains('hidden'); }, sel, { timeout: t });
  const waitStep = (sub, t = 60000) => page.waitForFunction((s) => { const c = document.querySelector('#stepcard'); return c && !c.classList.contains('hidden') && document.querySelector('#scTitle').textContent.includes(s); }, sub, { timeout: t });
  const demo = (d) => page.evaluate((x) => { window.__demo = x; }, d);
  const nav = (id) => page.evaluate((z) => { document.querySelector(`#wsnav button[data-nav="${z}"]`)?.click(); }, id);
  const doCard = async (d, r = 3) => { await demo(d);
    await page.waitForFunction(() => !document.querySelector('#ckShot').classList.contains('hidden'), null, { timeout: 30000 });
    await page.waitForTimeout(400); await page.click('#ckShot');
    await page.waitForFunction(() => !document.querySelector('#ckNext').classList.contains('hidden') || !document.querySelector('#ckRetry').classList.contains('hidden'), null, { timeout: 30000 });
    if (await page.evaluate(() => !document.querySelector('#ckRetry').classList.contains('hidden'))) { if (r <= 0) return; await page.click('#ckRetry'); return doCard(d, r - 1); } };
  await page.setViewportSize({ width: 1280, height: 800 });
  await page.goto('http://localhost:8642/v5.html?demo=1&ws=1&seat=93');
  await page.evaluate(() => localStorage.clear()); await page.reload();
  await page.click('#start');
  await waitStep('Научим ИИ ладони', 90000);
  await page.waitForTimeout(900);
  await shot('hub-1-lesson-card-with-nav');
  await demo({ cls: 0, size: 1.0, present: true }); await page.click('#scGo');
  await page.waitForFunction(() => document.querySelectorAll('#gdots i.on').length >= 2, null, { timeout: 30000 });
  await nav('hub'); await waitVis('#hub'); await page.waitForTimeout(300);
  await shot('hub-2-early-locked');
  await nav('lesson');
  await page.waitForFunction(() => document.querySelectorAll('#gdots i.on').length >= 6, null, { timeout: 40000 });
  await waitStep('6 ладоней собрано'); await page.click('#scGo');
  await waitStep('Теперь кулаки'); await demo({ cls: 1, size: 0.3, present: true }); await page.click('#scGo');
  await waitStep('ИИ обучен'); await page.click('#scGo');
  await doCard({ cls: 0, size: 1.0, present: true }); await page.click('#ckNext');
  await doCard({ cls: 1, size: 0.3, present: true }); await page.click('#ckNext');
  await doCard({ cls: 0, size: 0.3, present: true }); await page.click('#ckNext');
  await waitVis('#hypo'); await page.fill('#hypotext', 'размер'); await page.click('#hypoNext');
  await waitVis('#guess'); await page.locator('#guessbtns .choice', { hasText: 'размер' }).click();
  await waitVis('#lock'); await page.fill('#lockcode', '4712'); await page.click('#lockNext');
  await waitVis('#reveal');
  await page.click('#fixBtn'); await waitVis('#fixpick');
  await page.locator('#fixbtns .choice', { hasText: 'Наоборот' }).click();
  await waitStep('Маленькие ладони'); await demo({ cls: 0, size: 0.3, present: true }); await page.click('#scGo');
  await waitStep('большие кулаки'); await demo({ cls: 1, size: 1.0, present: true }); await page.click('#scGo');
  await waitStep('Починка готова'); await page.click('#scGo');
  await doCard({ cls: 0, size: 1.0, present: true }); await page.click('#ckNext');
  await doCard({ cls: 1, size: 0.3, present: true }); await page.click('#ckNext');
  await doCard({ cls: 0, size: 0.3, present: true }); await page.click('#ckNext');
  await doCard({ cls: 1, size: 1.0, present: true }); await page.click('#ckNext');
  await waitVis('#final');
  await page.click('#fSurvey'); await waitVis('#survey');
  await page.fill('#svtext', '33'); await page.click('#svNext');
  for (let i = 0; i < 3; i++) { await page.fill('#svtext', 'ответ'); await page.click('#svNext'); await page.waitForTimeout(200); }
  await waitVis('#final');
  await nav('hub'); await waitVis('#hub'); await page.waitForTimeout(300);
  await shot('hub-3-all-open');
  await nav('album'); await waitVis('#labgal'); await page.waitForTimeout(300);
  await shot('hub-4-album-editable');
  await page.click('#labgalClose');
  await nav('range');
  await page.waitForFunction(() => !document.querySelector('#checkui').classList.contains('hidden'));
  await page.waitForTimeout(700);
  await shot('hub-5-range');
  return log.join('\n');
}
